const selectors = {
	form: '#productForm', // ID of the form
	variantSelectId: 'variant-select', // Variant select ID required to initialize Shopify.OptionSelectors
	productOptionSelect: '.product-option-select' // Form element for the option selection of the Product. Should trigger a 'change' event.
}

const productJSON = JSON.parse(document.getElementById('product-json').innerHTML);
new Shopify.OptionSelectors(selectors.variantSelectId, { product: productJSON, onVariantSelected: selectCallback, enableHistoryState: true });


/**
 * Function that runs on each variant change
 * 
 * @param {*} variant 
 */
function selectCallback(variant){
  console.log(variant)
}


/**
 * Function that serializes a form and returns an object with key: value pairs for each form field
 *
 * @param {*} form - HTMLFormElement
 * @returns
 */
function serializeForm(form) {
	var obj = {};
	var formData = new FormData(form);
	for (var key of formData.keys()) {
		obj[key] = formData.get(key);
	}
	return obj;
}


const productForm = document.querySelector(selectors.form)
productForm.addEventListener('submit', function(e){
	e.preventDefault()
	const formData = serializeForm(this)
	CartJS.addItem(formData.id, formData.quantity, {}, {
		success: (data, textStatus)=>{
			console.log('Added to cart: ', data, textStatus)
		}, 
		error: (jqXHR, textStatus, errorThrown)=> {
			console.log('Error in adding to cart: ', errorThrown)
		}
	})
})


/**
 Listen to change events in the form option selectors, when changed, trigger change event in the select generated by Shopify.OptionSelectors. 
 */
Array.from(document.querySelectorAll(selectors.productOptionSelect)).map((el)=>{
	el.addEventListener('change', function(e) {
		const formData = serializeForm(productForm)
		const optionIndex = e.target.getAttribute('name')		
		const formOptions = Object.keys(formData).filter(key=>/^option(1|2|3)/.test(key))
		
		const curVariant = productJSON.variants.find((variant)=>{
			let res = true
			formOptions.map((option)=>{res = res && formData[option] == variant[option]})
			return res
		})
		
		
		/**
		 * NOTE: Elements with the class: .single-option-selector are generated by Shopify.OptionSelectors
		*/
		const variantSelect = document.querySelector(`.single-option-selector[data-option=${optionIndex}]`)
		variantSelect.value = curVariant[optionIndex]
		variantSelect.dispatchEvent(new Event("change"))
	})
})